repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        args: ['--plugin=prettier-plugin-organize-imports']
        types_or: [javascript, ts]
        additional_dependencies:
          - prettier@^2.8.4
          - 'prettier-plugin-organize-imports@^3.2.2'
